# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-20 16:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0006_auto_20170820_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='zip',
            field=models.IntegerField(default='00000', null=True),
        ),
    ]
