# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-22 14:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0012_auto_20170821_1859'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='contacts',
            unique_together=set([('last_name', 'wallet')]),
        ),
    ]
