# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-22 14:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exchange', '0013_auto_20170822_1706'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='contacts',
            unique_together=set([('friend', 'wallet')]),
        ),
    ]
